services:
  - type: web
    name: soft-sme-backend
    runtime: docker
    plan: starter
    startCommand: ./render-start.sh
    disk:
      name: ai-cache
      mountPath: /var/lib/render/ai-cache
      sizeGB: 20
    envVars:
      - key: PORT
        value: "10000"
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        fromDatabase:
          name: soft-sme-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: soft-sme-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: soft-sme-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: soft-sme-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: soft-sme-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: "*"
      - key: TRANSFORMERS_CACHE
        value: "/var/lib/render/ai-cache/huggingface"
      - key: HUGGINGFACE_HUB_CACHE
        value: "/var/lib/render/ai-cache/huggingface"
      - key: HF_HOME
        value: "/var/lib/render/ai-cache/huggingface"
      - key: XDG_CACHE_HOME
        value: "/var/lib/render/ai-cache"
      - key: PIP_CACHE_DIR
        value: "/var/lib/render/ai-cache/pip"
      - key: UV_CACHE_DIR
        value: "/var/lib/render/ai-cache/uv"

databases:
  - name: soft-sme-db
    databaseName: soft_sme_db
    user: soft_sme_user
