services:
  - type: web
    name: soft-sme-backend
    env: node
    buildCommand: ./render-build.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        fromDatabase:
          name: soft-sme-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: soft-sme-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: soft-sme-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: soft-sme-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: soft-sme-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: "*"

databases:
  - name: soft-sme-db
    databaseName: soft_sme_db
    user: soft_sme_user 